-- 81 ili (plaka kodu) shipping_zones tablosuna seed eder.
-- Not: Şu anda DB'de sadece 5 il var (6,10,34,35,41). Wizard'da tüm illeri görmek için önce bu scripti çalıştırın.
-- Güvenli: city_code üzerinden UPSERT yapar.

INSERT INTO shipping_zones (city_code, city_name, base_shipping_cost, is_active)
VALUES
  (1,  'Adana', 0, true),
  (2,  'Adıyaman', 0, true),
  (3,  'Afyonkarahisar', 0, true),
  (4,  'Ağrı', 0, true),
  (5,  'Amasya', 0, true),
  (6,  'Ankara', 0, true),
  (7,  'Antalya', 0, true),
  (8,  'Artvin', 0, true),
  (9,  'Aydın', 0, true),
  (10, 'Balıkesir', 0, true),
  (11, 'Bilecik', 0, true),
  (12, 'Bingöl', 0, true),
  (13, 'Bitlis', 0, true),
  (14, 'Bolu', 0, true),
  (15, 'Burdur', 0, true),
  (16, 'Bursa', 0, true),
  (17, 'Çanakkale', 0, true),
  (18, 'Çankırı', 0, true),
  (19, 'Çorum', 0, true),
  (20, 'Denizli', 0, true),
  (21, 'Diyarbakır', 0, true),
  (22, 'Edirne', 0, true),
  (23, 'Elazığ', 0, true),
  (24, 'Erzincan', 0, true),
  (25, 'Erzurum', 0, true),
  (26, 'Eskişehir', 0, true),
  (27, 'Gaziantep', 0, true),
  (28, 'Giresun', 0, true),
  (29, 'Gümüşhane', 0, true),
  (30, 'Hakkari', 0, true),
  (31, 'Hatay', 0, true),
  (32, 'Isparta', 0, true),
  (33, 'Mersin', 0, true),
  (34, 'İstanbul', 0, true),
  (35, 'İzmir', 0, true),
  (36, 'Kars', 0, true),
  (37, 'Kastamonu', 0, true),
  (38, 'Kayseri', 0, true),
  (39, 'Kırklareli', 0, true),
  (40, 'Kırşehir', 0, true),
  (41, 'Kocaeli', 0, true),
  (42, 'Konya', 0, true),
  (43, 'Kütahya', 0, true),
  (44, 'Malatya', 0, true),
  (45, 'Manisa', 0, true),
  (46, 'Kahramanmaraş', 0, true),
  (47, 'Mardin', 0, true),
  (48, 'Muğla', 0, true),
  (49, 'Muş', 0, true),
  (50, 'Nevşehir', 0, true),
  (51, 'Niğde', 0, true),
  (52, 'Ordu', 0, true),
  (53, 'Rize', 0, true),
  (54, 'Sakarya', 0, true),
  (55, 'Samsun', 0, true),
  (56, 'Siirt', 0, true),
  (57, 'Sinop', 0, true),
  (58, 'Sivas', 0, true),
  (59, 'Tekirdağ', 0, true),
  (60, 'Tokat', 0, true),
  (61, 'Trabzon', 0, true),
  (62, 'Tunceli', 0, true),
  (63, 'Şanlıurfa', 0, true),
  (64, 'Uşak', 0, true),
  (65, 'Van', 0, true),
  (66, 'Yozgat', 0, true),
  (67, 'Zonguldak', 0, true),
  (68, 'Aksaray', 0, true),
  (69, 'Bayburt', 0, true),
  (70, 'Karaman', 0, true),
  (71, 'Kırıkkale', 0, true),
  (72, 'Batman', 0, true),
  (73, 'Şırnak', 0, true),
  (74, 'Bartın', 0, true),
  (75, 'Ardahan', 0, true),
  (76, 'Iğdır', 0, true),
  (77, 'Yalova', 0, true),
  (78, 'Karabük', 0, true),
  (79, 'Kilis', 0, true),
  (80, 'Osmaniye', 0, true),
  (81, 'Düzce', 0, true)
ON CONFLICT (city_code) DO UPDATE
SET
  city_name = EXCLUDED.city_name,
  is_active = EXCLUDED.is_active;

-- Kontrol
SELECT COUNT(*) AS zone_count FROM shipping_zones;


