-- Tekno Ürünleri - Toplu Ekleme
-- Generated by PDF Parser
-- İndirimler: %40 + %8, Kar: %10

-- 1. TEKNOİZOFİX - Yapıştırıcı (25 KG)
-- Liste: 8.80 TL/KG → Satış: 5.34 TL/KG (Paket: 133.58 TL)
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active
) VALUES (
  6, 1, 'TEKNOİZOFİX', 'Yapıştırıcı', 'KG', 25,
  133.58, true, true, 40, 8,
  true, true
);

-- 2. TEKNOİZOSIVA - Sıva (25 KG)
-- Liste: 9.70 TL/KG → Satış: 5.89 TL/KG (Paket: 147.25 TL)
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active
) VALUES (
  6, 2, 'TEKNOİZOSIVA', 'Sıva', 'KG', 25,
  147.25, true, true, 40, 8,
  true, true
);

-- 3. TEKNODEKO KALIN (2 MM) - Dekoratif Sıva (25 KG)
-- Liste: 12.20 TL/KG → Satış: 7.41 TL/KG (Paket: 185.20 TL)
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active, dowel_length
) VALUES (
  6, 7, 'TEKNODEKO KALIN (2 MM)', 'Deko Kalın', 'KG', 25,
  185.20, true, true, 40, 8,
  true, true, 2
);

-- 4. FİLE 4X4 - Mantolama Filesi (160 M²)
-- Liste: 32.00 TL/M² → Satış: 19.43 TL/M² (Paket: 3108.86 TL)
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active
) VALUES (
  6, 4, 'FİLE 4X4', 'File', 'M²', 160,
  3108.86, true, true, 40, 8,
  true, true
);

-- 5. FİLELİ PVC KÖŞE PROFİLİ (1 MT)
-- Liste: 16.60 TL/MT → Satış: 10.08 TL/MT
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active
) VALUES (
  6, 5, 'FİLELİ PVC KÖŞE PROFİLİ', 'Fileli Köşe', 'MT', 1,
  10.08, true, true, 40, 8,
  true, true
);

-- 6. ÇELİK ÇİVİLİ DÜBEL 115 MM (1 ADET)
-- Liste: 4.50 TL/ADET → Satış: 2.73 TL/ADET
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active, dowel_length
) VALUES (
  6, 3, 'ÇELİK ÇİVİLİ DÜBEL 115 MM', 'Çelik Dübel 11.5cm', 'ADET', 1,
  2.73, true, true, 40, 8,
  true, true, 115
);

-- 7. ÇELİK ÇİVİLİ DÜBEL 155 MM (1 ADET)
-- Liste: 5.20 TL/ADET → Satış: 3.16 TL/ADET
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active, dowel_length
) VALUES (
  6, 3, 'ÇELİK ÇİVİLİ DÜBEL 155 MM', 'Çelik Dübel 15.5cm', 'ADET', 1,
  3.16, true, true, 40, 8,
  true, true, 155
);

-- 8. PLASTİK ÇİVİLİ DÜBEL 10 CM (1 ADET)
-- Liste: 2.10 TL/ADET → Satış: 1.28 TL/ADET
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active, dowel_length
) VALUES (
  6, 3, 'PLASTİK ÇİVİLİ DÜBEL 10 CM', 'Plastik Dübel 10cm', 'ADET', 1,
  1.28, true, true, 40, 8,
  true, true, 100
);

-- 9. PLASTİK ÇİVİLİ DÜBEL 12 CM (1 ADET)
-- Liste: 2.40 TL/ADET → Satış: 1.46 TL/ADET
INSERT INTO accessories (
  brand_id, accessory_type_id, name, short_name, unit, unit_content,
  base_price, is_for_eps, is_for_tasyunu, discount_1, discount_2,
  is_kdv_included, is_active, dowel_length
) VALUES (
  6, 3, 'PLASTİK ÇİVİLİ DÜBEL 12 CM', 'Plastik Dübel 12cm', 'ADET', 1,
  1.46, true, true, 40, 8,
  true, true, 120
);

-- NOT: TEKNODEKO İNCE ürünü parse edilmedi, manuel olarak eklenebilir
